### ISSUE TITLE
Modify programming for last block on /careers/ to allow an iframe

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#112]
The careers page is receiving an edit. The entries in the CPT Job Openings will all be marked private, removing them from the information printed on the screen. The new iframe for searching available positions can then be placed into the bottom section, Page Additional Fields," which currently holds the employment disclaimer. 

Please adjust the code for the Page Additional Fields section to accept the following iframe:

`<iframe id="resumator-job-frame" class="resumator-advanced-widget" src="//automatedlogisticssystems.applytojob.com/apply/jobs/" name="resumator-job-frame" width="100%" frameborder="0" scrolling="no"></iframe><script>function resizeResumatorIframe(height,nojump){if(nojump== 0){window.scrollTo(0,0);}document.getElementById("resumator-job-frame").height = parseInt(height)+20;}</script>
`
That new block should now sit nicely under the H2, JOB OPENINGS AT ALS. It should extend from left to right of the page container.

Here is a mockup:
![image](https://user-images.githubusercontent.com/8271108/153228941-2b55de97-5bb3-41cf-8f64-f973b57f4f42.png)

**Comment by d4mation** [comment]
The field itself supported it, but Editors don't have the ability to use `<iframe>` or `<script>` tags for security reasons.

I've adjusted it so that Editors are able to use those tags now. 

Given the security implications, it should be stressed that all Editors should be using strong passwords.

As an extra note, in order to paste in that code you will need to click the "Source Code" button given how ACF handles the WYSIWYG editor. There isn't a "Text" tab to enable. 

![image](https://user-images.githubusercontent.com/7770631/153262643-93735a34-5dfa-4a9d-89f5-1835db0b1a43.png)

**Comment by BigActual** [comment]
Understood
