### ISSUE TITLE
Button bug fix

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#20]
Notice the design issue in the button on my display: ![image](https://cloud.githubusercontent.com/assets/8271108/14465441/0c813a86-00a1-11e6-8f02-14d249ebc7e8.png)

Chrome (latest), Windows 7 only. Safari, Opera & Firefox are fine.

**Comment by d4mation** [comment]
Interesting. I tested this on Chrome in Windows without any issues, but granted that was on Windows 10. 

What resolution is your screen set to?

**Comment by BigActual** [comment]
1920*1080

**Comment by d4mation** [comment]
I'll see if I can replicate this. My display is 1080p as well on my personal desktop running Windows 10.

**Comment by d4mation** [comment]
Just to document this:

This was caused by a browser having its internal font-size scaling set higher than the default.

Since the neat little "arc" effect on the buttons is produced by pre-drawn SVGs based on the buttons being a specific size, I had to set the `font-size`s of any buttons with that "arc" to be a static pixel number rather than being dynamically calculated via an `em` value.

The smallest possible `font-size` for these buttons is `14.4px`, which is still very readable for being the smallest size. If needed, the version of the SVG used for this size "arc" button can be redrawn to utilize a larger `font-size`.

The font sizes are as follows:
- `tiny`: `14.4px`
- `small`: `19.2px`
- `default`: `23.52px`
- `large`: `32px`

This change only effects the "arc" buttons, so it won't affect accessibility for any other aspect of the site.
