### ISSUE TITLE
Animate loading of home page elements

### ISSUE THREAD

**Issue by brashrebel** [automatedlogistics/Theme2016#23]
Check out what Joel did with the loading of everything on the home page of realbigmarketing.com. I think there's cool potential on the ALS site to animate the red line as you scroll down. The http://renderwp.com/ site also has some nice animations as you move down the page. I think we could just spruce it up.

**Comment by d4mation** [comment]
Took a lot of tweaking, but I managed to get [WOW.js](http://mynameismatthieu.com/WOW/) working nicely with [Motion UI](http://foundation.zurb.com/sites/docs/motion-ui.html). The sparse documentation for using them together worked well enough for Animations (Spinning, wiggling, etc.), but not for Transitions (Fade in/out and such) so I had to figure out how to get that working.

The Timeline section (With the vertical red line) now subtly fades in each section as you scroll down. I'm going to see what other animations I can work in to spruce it up.

**Comment by d4mation** [comment]
Added in some slide-in animations for the CTA/Hero sections to bring their text into view and set the little Icon Buttons toward the top to expand to their full size. 

Everything works great on Mobile as far as waiting for them to be in-view before transitioning in, which is very nice.

**Comment by d4mation** [comment]
I didn't notice WOW.js had some paid licensing stuff at the bottom until after I implemented it, so I changed it up to use a modification of what http://renderwp.com/ is using.

Still works just as well, if not better. Have to run some nasty regex on the Class Names of elements to determine which Motion UI functions to call, but it works and it should be easy to animate anything from here on out.

**Comment by brashrebel** [comment]
Great! What do you think about my silly red line idea?

**Comment by d4mation** [comment]
Ah, I misunderstood you about the line. 

I might be able to figure something out for that. It is made using a `:before` pseudo element on the Container.

![image](https://cloud.githubusercontent.com/assets/7770631/14613750/d23aad4c-056b-11e6-887d-11aefdb969bc.png)

**Comment by brashrebel** [comment]
It isn't critical. But I do want some flourishes. Although, please hold on ALS for the time being. This is in a review phase until...a couple more days.

**Comment by BigActual** [comment]
As we scroll past images that aren't already full width, let's make them enlarge slightly. For example, the first image in the redline section is already a bit larger. It's actually too large for what I'm thinking. But if each of the images could start at the size of the second, third and fourth item and enlarge to something a little bigger. That would be ideal for the purposes I'm envisioning.

**Comment by d4mation** [comment]
Ah, yeah, the first image got swapped in at some point and since it is much larger than the others it is getting scaled down to a `600px` width which I set as the maximum for that section. All the other images aren't even big enough to get effected by that normally.

The scaling animation sounds really neat though. I'm going to look into implementing that.

**Comment by d4mation** [comment]
I just added a slight scaling animation to the images within the Home Timeline and I altered the size of the images to max out at `500px` to help them appear to be closer to the same size.

I tried to record a GIF of it in action, but unfortunately [Recordit](http://recordit.co/) will only let me record in 4fps which couldn't show it very well. The changes are up on the server now and if needed, it can be very easily reverted.

**Comment by BigActual** [comment]
No worries. Can you make it so that no matter what's loaded, it presents at the correct finished size? This way the user can be off a bit. Oddly stretched images have to be reloaded manually by the user who's loading them of course, but if they're proportionately correct they'd present correct.

**Comment by d4mation** [comment]
Do you mean having the images scale proportionately? That's how it works currently. If the image is wider than `500px` it scales down proportionately to have a width of `500px`.

The other images below are all much wider than they are tall (Similar to how the images were in #39) but they are very small pixel-wise so there isn't any room to crop them down nicely. The second image in the Timeline is `424x179` at full size for example.

I can change it so that the images scale down after `400px` which should cover more use cases and keep the edges more neat. However, this won't solve issues with some images being smaller vertically than others. It would also bring the Timeline itself closer to the center of the page and leave more whitespace on the sides.

Do we have different images that we can use? With the exception of the top image in the Timeline all the other ones were images that we were provided with along with the initial mockups.

**Comment by BigActual** [comment]
Let's finalize this. Have the final image maintain ratio and have the final output 424x179 which means using a combination of scaling and cropping. If cropping needs to occur, have it cropped evenly on both ends.

**Comment by d4mation** [comment]
Ended up cropping it to `75%` height of the original image and then bumping it down a bit to help keep things within the frame. In order to keep the proportion similar, some of the image had to be lost toward the bottom. However, you can still see the ALS logo on their shirts. Now the regular resizing rules that scale things make them all look the same size.

![image](https://cloud.githubusercontent.com/assets/7770631/15334455/3ac7ee6a-1c3c-11e6-8577-bc8ce0f538b9.png)

**Comment by BigActual** [comment]
Yay. Thanks. PS. Feel free to close these with your commit and I'll reopen if needs be. Unless that contradicts something you're doing on purpose.

**Comment by d4mation** [comment]
In this case it wasn't related to a commit in the codebase, so I wanted to ensure you saw it first before I closed it since it was a semi-destructive change. 👍
