### ISSUE TITLE
Styling Suggestions

### ISSUE THREAD

**Issue by skarritt** [automatedlogistics/Theme2016#26]
Greetings Eric and Kyle,
Steve asked me to jump in with comments on nit-picky styling issues.  Here are a couple - pasted below.  within each class/ID that I'm commenting on, I've only included the parameter that I'm suggesting to be changed.  Please let me know if any of these don't make sense.  I'll continue to scour and throw little tweaky things back your way.

.button.with-arc.secondary {
    text-shadow: 0px 0px 6px rgba(0, 0, 0, 0.79);
}

.home #home-timeline .container .row .timeline-dot {
    width: 16px;
    height: 16px;
    margin-left: -8px;
}

.connect .social-icon {
    font-size: 2.5em;
    line-height: 1em;
}

input[type="submit"] {
        /\* width: something other than 100%  -- e.g. look at the Connect page;  */
}

**Comment by d4mation** [comment]
I've gone ahead and made all of these adjustments and they are on the test site.

You mentioned the Connect Page in particular for Submit Buttons, but what do you think about how it appears for the Search Form Submit Buttons? It seems to work well full-width there.

![image](https://cloud.githubusercontent.com/assets/7770631/14784210/615d09c4-0ac2-11e6-8efd-37009a5012ff.png)

![image](https://cloud.githubusercontent.com/assets/7770631/14784223/7164fe3a-0ac2-11e6-9747-f77e3ac72894.png)

For the Connect Page's Form I made the button 33% width and aligned it to the right:

![image](https://cloud.githubusercontent.com/assets/7770631/14784257/99a6f6dc-0ac2-11e6-96f0-3e3a4b1a21f1.png)

**Comment by d4mation** [comment]
Referencing #36 and #40.

**Comment by BigActual** [comment]
please align left

**Comment by BigActual** [comment]
Global change. All form buttons align left.

**Comment by d4mation** [comment]
Went ahead and set the Connect Form to use the same Global Styling that is hitting the Search Overlay Form so it will align left.

![image](https://cloud.githubusercontent.com/assets/7770631/15150154/12feb6b8-169a-11e6-9bf9-b476ed839707.png)

For the Search Forms within Sidebars (Such as on 404 Pages), it maxes out in size on every screen size I've tested since the sidebar's width is less than `300px`. (`max-width` of `300px` as per #36)

![image](https://cloud.githubusercontent.com/assets/7770631/15150394/fe8f26a8-169a-11e6-88a6-8e5a32c0a7da.png)

![image](https://cloud.githubusercontent.com/assets/7770631/15150409/111cda22-169b-11e6-9e41-5f394e231681.png)

![image](https://cloud.githubusercontent.com/assets/7770631/15150300/9dc469fa-169a-11e6-815d-2b858ca458d6.png)

Having the Submit button within the Sidebar fitting the full-width of the container looks pretty good in this instance I think, but we can try to adjust it to have the same left-aligned appearance as well.

**Comment by BigActual** [comment]
Sounds good. Thanks.
