### ISSUE TITLE
About Us 

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#27]
On the home page, in the top right menu, could we add an "About Us" section. Currently you have to scroll to the bottom of the page to see this is available information

Thanks
Owie

**Comment by d4mation** [comment]
I added it to the top menu as a dropdown so that links to Staff, About Us, and Careers are easily accessable in the same way that they are in the footer.

![image](https://cloud.githubusercontent.com/assets/7770631/14861905/2edac7c2-0c7d-11e6-923a-50e0541810e1.png)

Is that what you're looking for?

You may need to hard-refresh for the fix that I applied to show for you. (`CTRL+F5` on a PC, `CMD+SHIFT+R` on a Mac)

**Comment by owielanctot** [comment]
Yep that's it! Thank you
