### ISSUE TITLE
"Our Products" Tab

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#28]
In the blue bar in the middle/bottom of the home page I think there should be a circle tab option added called “Products.”  It would be to the left of the “shippers” circle tab on the blue bar. This is the bar below the zooming cars picture

Within this tab it will take you to our five main products:
Brokerage
CT
Consol/Deconsol
Engineering
Warehousing 

Thanks!

**Comment by brashrebel** [comment]
Good idea @owielanctot, though this is really a content question. I think we'll need to discuss this more deeply before implementing as it does not line up with what our original strategic plan and research outlined.

I agree that those products (we've also referred to them as "services") are very important to highlight. However, I don't necessarily think that is the right place to do so. The three items listed there are _personas_ and products would be unlike them. The point of that section of the site, which will likely evolve over time, is to allow visitors to identify which audience group they fall into. No visitor is a "product". It introduces a possible point of confusion/hesitation because they could be _both_ a shipper _and_ someone looking for products.

So that's the short version of my thoughts. I think another place should be sought to promote the products/services. But we can discuss further for sure.

**Comment by owielanctot** [comment]
I see what you're saying @brashrebel, if that is the case and the train of though we would like to continue with, we need to change "Shipper" to something like "Customer." But I don't like customer. I would rather have it say products. 

Leaving it as is pigeonholes our site visitors into just one product

**Comment by owielanctot** [comment]
@brashrebel Hey Kyle- Just talked with Paul- changing "Shippers" to "Customers" should take care of the immediate need. Thanks

**Comment by owielanctot** [comment]
Update "Shippers" to "Customers"

**Comment by BigActual** [comment]
Referenced in #42. Will mark as complete when changed.
