### ISSUE TITLE
Employment Landing Page

### ISSUE THREAD

**Issue by d4mation** [automatedlogistics/Theme2016#3]
Include Employment Loop [category:all] Loop and area for video
- [x] Employee testimonials
- [x] List of current Job openings (Employment Single feed here.  If no jobs, the section is hidden)

**Comment by d4mation** [comment]
Still need to figure out how to add the extra buttons on the side without ruining Accordion functionality.

![image](https://cloud.githubusercontent.com/assets/7770631/14126895/15c1bbc6-f5e2-11e5-961a-3044c9b229c5.png)

**Comment by skarritt** [comment]
Does this need to be done differently?  I'd be TOTALLY ok with deleting the "Details" button (because the majority of the details are in the accordion window) and we can move the "Apply Now" into the accordion below the job details.  Run this by and @brashrebel and loop me back in if needs more input.

**Comment by d4mation** [comment]
What do you think, @brashrebel?

**Comment by BigActual** [comment]
That's fine by me @d4mation.

**Comment by brashrebel** [comment]
Sure, sounds good.
