### ISSUE TITLE
Right Sidebar with widgets for Carriers Page

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#34]
For calls to action. Contact Us with correct phone number  and then another button for the Connect Page.

Thinking of this, if they click the email link, how about bringing up the form in it's own window with focus on the form, like the search function.

**Comment by brashrebel** [comment]
I'd generally label that as an enhancement for a future milestone (the form like search thing) but it sounds nice and would be consistent with the search feature so let's incorporate that.

The other stuff I don't get. You need empty sidebars just in case? What's going there exactly?

**Comment by d4mation** [comment]
The sidebar has been added and can be easily managed via Widgets in the backend.

Which Email Link should be popping up a special form? Right now I have a button that links to the "Connect" page which has the email form, but I may be able to get something like the Search Overlay working.

**Comment by BigActual** [comment]
Resources for @d4mation 
[new-prospect-V3.pdf](https://github.com/automatedlogistics/Theme2016/files/286628/new-prospect-V3.pdf)
[interested-prospect-V3.pdf](https://github.com/automatedlogistics/Theme2016/files/286630/interested-prospect-V3.pdf)

**Comment by d4mation** [comment]
@BigActual 

Replying here for both this Issue and #32 as their implementations are similar.

I've added some Fields to the Customers and Carrier Pages that allow for just about anything to be placed in them allowing a lot of freedom for this section. The top of the Fields section says "Customers/Carriers Sidebar" but that's only because the Fields are being re-used. They are entirely separate. This replaces the "Widget" implementation as we talked on the phone the other day and decided that this would likely be the best way to handle it.

![image](https://cloud.githubusercontent.com/assets/7770631/15613705/d1629a8c-2402-11e6-959c-0fe00ab260fd.png)

Since a CTA can include a large number of different things (Headers, text, buttons, file downloads, etc.) I figured a WYSIWYG editor would be the best in this situation.

I've also added a little button to the WYSIWYG editors site-wide so that those fancy little buttons you see all over the site can be easily added anywhere (including in these CTA Sidebars):

![image](https://cloud.githubusercontent.com/assets/7770631/15613765/32c8d782-2403-11e6-8e58-8d4724def707.png)

The "Phone Number" field automatically creates a `tel:` link using the Phone Number provided and places it below the CTA. This could optionally be left empty&mdash;I just like to ensure that phone numbers are actionable on Mobile.

Here's a quick example on the Customers Page. I felt that it needed some kind of backdrop to differentiate it from the rest of the Content.

![image](https://cloud.githubusercontent.com/assets/7770631/15613858/97f2c398-2403-11e6-9f58-00024a45513d.png)

Here's the Carriers Page with a button added for the Connect Page:

![image](https://cloud.githubusercontent.com/assets/7770631/15613961/19ec512a-2404-11e6-932a-249c7b776a98.png)

These changes are now up on the Test Site.

If there's anything else I should add/this needs to do, let me know. I'm going to close these Issues with this Commit.
