### ISSUE TITLE
About Us Page Needs to exist

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#35]
For discussion: 
A little blurb about the team with a link to the team
A little blurb about the history with a link to the history.

**Comment by brashrebel** [comment]
Who's doing this? Sounds like content so I can't assign it to a developer.

**Comment by d4mation** [comment]
There technically is an About Us page right now [here](http://alsintersite11.wpengine.com/about-us/). All of the mock-ups pointed toward representing it in the Menus as "Our History" under a more global "About Us" umbrella. 

The Page Title and Slug for "Our History" are both "About Us" currently.

Should there be a separate "About Us" page?

**Comment by BigActual** [comment]
No, good catch. Kevin and I were recording issues as we came across them during our meeting. Just link the menu item to the existing page. Thx.

**Comment by d4mation** [comment]
All set!

In the Main Navigation, should I remove the link to "Our History" since the "About Us" tab itself now links to the same page? I figure it could be confusing to users if they click "About Us" and it shows that the current page is "Our History"

![image](https://cloud.githubusercontent.com/assets/7770631/15014945/f9d183e0-11d6-11e6-9aac-468a1cb29434.png)
