### ISSUE TITLE
Red arrow

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#37]
Not showing correctly in Firefox, Chrome or IE on Windows. It's completely missing on Firefox and Chrome for me. In IE, it looks like this: 
![image](https://cloud.githubusercontent.com/assets/8271108/14998090/1f05f984-1150-11e6-9bd5-da83926f4f7c.png)

Kevin says that on his machine it's not aligned correctly. Is this element required or can we achieve the same goal with a better ux element?

**Comment by d4mation** [comment]
The Red Arrow was added in as a suggestion in #24. By the time it reaches 50% up the page it is intended to become entirely transparent. I'm entirely open to different UX suggestions&mdash;it is a weird issue since different size screens will see more or less of the following section on page-load which could lead to it being less necessary anyway.

It shows in Chrome and Firefox for me:
![image](https://cloud.githubusercontent.com/assets/7770631/14998182/b08c4ce6-1150-11e6-9f0b-d34a84c24ca0.png)

**Comment by BigActual** [comment]
There's a problem with this in general. I'm going to reopen #24.
