### ISSUE TITLE
Technical glitch on android / Logo Menu overlap

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#49]
![screenshot_20160517-134246](https://cloud.githubusercontent.com/assets/8271108/15334450/38976ecc-1c3c-11e6-970c-8b099b179f25.png)

Landscape view logo is covered by menu.

**Comment by d4mation** [comment]
Interesting, doesn't seem to have that problem on my Nexus 5. Do we know what Android Device this is in particular? (E.G., is it a Tablet/Phablet rather than a regular-sized Smart Phone). I'm going to try to find some breakpoints in the meantime to test.

![image](https://cloud.githubusercontent.com/assets/7770631/15334549/a95b54a2-1c3c-11e6-9c66-ac6fe9c03f98.png)

**Comment by BigActual** [comment]
Yes, Galaxy Note 5.

**Comment by d4mation** [comment]
I think I may have fixed this. I had to add a custom entry into the Chrome Dev Tools to emulate a Galaxy Note 5 since it isn't normally an option. Unfortunately all I really had to go off of was [this Stack Overflow post](http://stackoverflow.com/questions/34422011/how-do-i-write-media-query-for-galaxy-note-5) as the Note 5 seems to be too new to be in any Viewport Databases I know of.

It seems that the Galaxy Note 5 reports a width of `360px` to the browser but scales it by 3, so I'm checking against the number it is scaling by as it seems to be ignoring the width (`360px` should have definitely caused it to be recognized as a mobile phone otherwise) (Edit: Reports a width of `360px` while in Portrait)

![image](https://cloud.githubusercontent.com/assets/7770631/15335982/57c4300e-1c42-11e6-8084-626b3c3b523e.png)

I'm about to push this to the Server. The owner of the Note 5 will likely need to clear out the Cache in their browser to see any changes. I don't know if Samsung is still shipping their own modified browser or not rather than just using Google Chrome&mdash;If they are still doing that, this media query may not work unfortunately.

**Comment by BigActual** [comment]
No change. Hard refreshed.

**Comment by BigActual** [comment]
This is the chrome browser.

**Comment by d4mation** [comment]
Just to confirm I've got things set correctly, could you visit this on your Galaxy Note 5 and copy everything that it shows for you?

http://viewportsizes.com/mine/

**Comment by BigActual** [comment]
412 x 652 portrait
732 X332 landscape

Mozilla/5.0 (Linux; Android 6.0.1; SM-N920P Build/MMB29K)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Mobile
Safari/537.36

**Comment by d4mation** [comment]
I just pushed another change to the server. I'm targeting specifically up until a `733px` width for landscape screens. It _should_ work now, unless Samsung is doing anything super funky with their devices these days.

![image](https://cloud.githubusercontent.com/assets/7770631/15359783/eed857cc-1cd8-11e6-9c4d-b6dba1610373.png)

**Comment by BigActual** [comment]
Checks out good here. Thanks.
