### ISSUE TITLE
Launch Site Monday, June 13th for party on the 14th.

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Theme2016#77]
Confirmed with Paul and Owie. The site is to be transferred on Monday with a Splash Screen. Administrators are to have access for testing purposes. All others will see the "It's almost here" screen. That screen is to contain:
- [x] Logo
- [x] Huge Countdown to Noon on Tuesday
- [x] If you can quickly make it snap, crackle and pop fireworks at Noon (Visual effects overlay, sweet. Otherwise, just go live. This is not that much of a horse and pony show and it's simply not a requirement.)
- [x] Contact information (Phone, Address)
- [x] Contact Us Form

Site is to go offline around 3 or 4 in the afternoon Monday and we are to test images. links, etc. per standard launch protocols before the client launch party on Tuesday. 

For the splash screen, I recommend repurposing the blue overlay used for the video accessed from the home screen. Let 'em see the site (sorta) but not be able to interact with it. This is only a suggestion.

@brashrebel Our instructions are to work directly with PC Solutions to access required platforms and information. I have no contact information.

**Comment by owielanctot** [comment]
@BigActual checking with PC solutions to see who your contact will be

**Comment by owielanctot** [comment]
Clint Wiltse – cwiltse@pcsolutionsnow.com 517-787-9934 @BigActual

**Comment by d4mation** [comment]
To help keep the codebase clean, I'm going to separate this temporary functionality out into a plugin. 

[It will be over here at automatedlogistics/Launch-Countdown.](https://github.com/automatedlogistics/Launch-Countdown)

**Comment by d4mation** [comment]
Can we get this logo (preferably as SVG)? 

I pretty much just don't want to have the ghost-logo behind it for this overlay. If I were to try to Photoshop it out, it would look blurry/have choppy edges once it is resized.

![image](https://cloud.githubusercontent.com/assets/7770631/15945455/a118f4ee-2e60-11e6-8c6a-324121a5660d.png)

**Comment by BigActual** [comment]
Sure. I'm unclear on which pieces you want. Please clarify, do you want me to include just the white, white and yellow, or more?

**Comment by d4mation** [comment]
All of it can be included, but I specifically want the solid white and the
yellow.

**Comment by BigActual** [comment]
Not to derail, is there a reason we didn't use a font for that yellow text instead of an image?

**Comment by d4mation** [comment]
No particular reason outside of that was the image we had and was provided
with the original mockups.

**Comment by BigActual** [comment]
[LOGO-NO-TAG-WHITE-YELLOW-NAME.zip](https://github.com/automatedlogistics/Theme2016/files/307934/LOGO-NO-TAG-WHITE-YELLOW-NAME.zip)

**Comment by d4mation** [comment]
Things are looking pretty great in my local environment.

Since this covers the screen at all times, we're limited to the screen height in pixels to work with which is why the contact information and contact form are in separate columns&mdash;as you scroll, this whole section moves with you.

This is all done via WordPress Widgets, so things can be easily changed or moved around at any time.

Once the countdown ends, the overlay disappears and the screen gets covered in fireworks for 5 minutes.

All I still need to implement is for it to not appear for admins, but that's a very quick fix. I'd say this is ready to go whenever on Monday 👍 

Edit: No longer shown for Admins unless they're actively changing the settings for it.

![image](https://cloud.githubusercontent.com/assets/7770631/15986390/d0848444-2fd4-11e6-9658-f049d70869af.png)

**Comment by d4mation** [comment]
Countdown is up on the site. Set to end tomorrow (6/14/16) at 12 PM EST.

**Comment by BigActual** [comment]
Please change the timer to 12:10. Their president wants to say a few words beforehand.

**Comment by d4mation** [comment]
Adjusted to 12:10 PM EST.
