### ISSUE TITLE
Add customer testimonials section on single products

### ISSUE THREAD

**Issue by brashrebel** [automatedlogistics/Theme2016#93]
Should be another red dot on the line below The ALS Difference.

**Comment by owielanctot** [comment]
@brashrebel Hey Kyle- I think this issue was added after a conversation you and I had. I may have misspoken and said customer testimonial, not to be confused with the actual customer testimonials that are on the right hand side of some pages, and meant to say 3rd party stories. Stylistically, you can tell me where this would be best suited for the page. It will probably be about 2 paragraphs long and include a company logo.

**Comment by brashrebel** [comment]
@owielanctot can you share an example with us?

**Comment by owielanctot** [comment]
I do not yet. But it will more than likely be similar to the Faurecia testimonial on the "History" page. Just longer. 

How would it look if we put it below the horizontal red line? on the LTL page? I'm open to suggestions

**Comment by BigActual** [comment]
Are these Case Studies? If so, should they eventually be tied to products and services in a programmatic sense? For example, have the title and an excerpt for the case study show up on the sidebar area of the product or service it relates to?

**Comment by brashrebel** [comment]
Yeah @owielanctot I don't think spending time on this will be very productive until we have the content for the first one completed. We need to understand the content in order to find the right place, design and layout for it.
