### ISSUE TITLE
Add employees to Product expert dropdown on products page

### ISSUE THREAD

**Issue by owielanctot** [automatedlogistics/Theme2016#98]
Need to add Will Ferris

**Comment by owielanctot** [comment]
His email is wferris@automatedlogistics.com and his photo is below

![will ferris](https://cloud.githubusercontent.com/assets/18618395/17223064/f6127b3a-54c8-11e6-8cfa-74db5b4616d8.jpg)

**Comment by d4mation** [comment]
The Dropdown actually shows any _Published_ Staff Members, so once his Staff Profile is published, he will automatically get added to that menu 👍

**Comment by owielanctot** [comment]
Most likley he will not be featured on the staff members page. If we create a staff page for him, but don't publish it, will we be able to use him on the products page? @d4mation

**Comment by d4mation** [comment]
Currently, no. That dropdown will only grab Published Staff. One big reason for this is because the Products Pages link back to the Staff Member listed as the "Expert".

For example, on the [LTL](http://automatedlogistics.com/product-service/less-than-truckload-ltl/) Page, if you click on Chris Strecker's photo or his name, it links back to his Staff Page.
